package com.fei.bean;

import java.io.Serializable;
import java.util.Date;

public class ApartmentNew implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.apartmentId
     *
     * @mbggenerated
     */
    private String apartmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.buildingId
     *
     * @mbggenerated
     */
    private String buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.bedroom
     *
     * @mbggenerated
     */
    private Integer bedroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.livingRoom
     *
     * @mbggenerated
     */
    private Integer livingRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.toltel
     *
     * @mbggenerated
     */
    private Integer toltel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.kitchen
     *
     * @mbggenerated
     */
    private Integer kitchen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.mainApartment
     *
     * @mbggenerated
     */
    private Integer mainApartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.saleNumber
     *
     * @mbggenerated
     */
    private Integer saleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.alreadySaleNumber
     *
     * @mbggenerated
     */
    private Integer alreadySaleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.apartDiscount
     *
     * @mbggenerated
     */
    private String apartDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.orientation
     *
     * @mbggenerated
     */
    private String orientation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.decorateSituation
     *
     * @mbggenerated
     */
    private Integer decorateSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.recommendReason
     *
     * @mbggenerated
     */
    private String recommendReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.shelves
     *
     * @mbggenerated
     */
    private Integer shelves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.deleteFlag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.averagePrice
     *
     * @mbggenerated
     */
    private String averagePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.commissionCalMethod
     *
     * @mbggenerated
     */
    private Integer commissionCalMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_apartment_new.commissionValue
     *
     * @mbggenerated
     */
    private Float commissionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.apartmentId
     *
     * @return the value of b_apartment_new.apartmentId
     *
     * @mbggenerated
     */
    public String getApartmentId() {
        return apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.apartmentId
     *
     * @param apartmentId the value for b_apartment_new.apartmentId
     *
     * @mbggenerated
     */
    public void setApartmentId(String apartmentId) {
        this.apartmentId = apartmentId == null ? null : apartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.buildingId
     *
     * @return the value of b_apartment_new.buildingId
     *
     * @mbggenerated
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.buildingId
     *
     * @param buildingId the value for b_apartment_new.buildingId
     *
     * @mbggenerated
     */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId == null ? null : buildingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.bedroom
     *
     * @return the value of b_apartment_new.bedroom
     *
     * @mbggenerated
     */
    public Integer getBedroom() {
        return bedroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.bedroom
     *
     * @param bedroom the value for b_apartment_new.bedroom
     *
     * @mbggenerated
     */
    public void setBedroom(Integer bedroom) {
        this.bedroom = bedroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.livingRoom
     *
     * @return the value of b_apartment_new.livingRoom
     *
     * @mbggenerated
     */
    public Integer getLivingRoom() {
        return livingRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.livingRoom
     *
     * @param livingRoom the value for b_apartment_new.livingRoom
     *
     * @mbggenerated
     */
    public void setLivingRoom(Integer livingRoom) {
        this.livingRoom = livingRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.toltel
     *
     * @return the value of b_apartment_new.toltel
     *
     * @mbggenerated
     */
    public Integer gettoltel() {
        return toltel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.toltel
     *
     * @param toltel the value for b_apartment_new.toltel
     *
     * @mbggenerated
     */
    public void settoltel(Integer toltel) {
        this.toltel = toltel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.kitchen
     *
     * @return the value of b_apartment_new.kitchen
     *
     * @mbggenerated
     */
    public Integer getKitchen() {
        return kitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.kitchen
     *
     * @param kitchen the value for b_apartment_new.kitchen
     *
     * @mbggenerated
     */
    public void setKitchen(Integer kitchen) {
        this.kitchen = kitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.area
     *
     * @return the value of b_apartment_new.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.area
     *
     * @param area the value for b_apartment_new.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.mainApartment
     *
     * @return the value of b_apartment_new.mainApartment
     *
     * @mbggenerated
     */
    public Integer getMainApartment() {
        return mainApartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.mainApartment
     *
     * @param mainApartment the value for b_apartment_new.mainApartment
     *
     * @mbggenerated
     */
    public void setMainApartment(Integer mainApartment) {
        this.mainApartment = mainApartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.saleNumber
     *
     * @return the value of b_apartment_new.saleNumber
     *
     * @mbggenerated
     */
    public Integer getSaleNumber() {
        return saleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.saleNumber
     *
     * @param saleNumber the value for b_apartment_new.saleNumber
     *
     * @mbggenerated
     */
    public void setSaleNumber(Integer saleNumber) {
        this.saleNumber = saleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.alreadySaleNumber
     *
     * @return the value of b_apartment_new.alreadySaleNumber
     *
     * @mbggenerated
     */
    public Integer getAlreadySaleNumber() {
        return alreadySaleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.alreadySaleNumber
     *
     * @param alreadySaleNumber the value for b_apartment_new.alreadySaleNumber
     *
     * @mbggenerated
     */
    public void setAlreadySaleNumber(Integer alreadySaleNumber) {
        this.alreadySaleNumber = alreadySaleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.apartDiscount
     *
     * @return the value of b_apartment_new.apartDiscount
     *
     * @mbggenerated
     */
    public String getApartDiscount() {
        return apartDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.apartDiscount
     *
     * @param apartDiscount the value for b_apartment_new.apartDiscount
     *
     * @mbggenerated
     */
    public void setApartDiscount(String apartDiscount) {
        this.apartDiscount = apartDiscount == null ? null : apartDiscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.orientation
     *
     * @return the value of b_apartment_new.orientation
     *
     * @mbggenerated
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.orientation
     *
     * @param orientation the value for b_apartment_new.orientation
     *
     * @mbggenerated
     */
    public void setOrientation(String orientation) {
        this.orientation = orientation == null ? null : orientation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.decorateSituation
     *
     * @return the value of b_apartment_new.decorateSituation
     *
     * @mbggenerated
     */
    public Integer getDecorateSituation() {
        return decorateSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.decorateSituation
     *
     * @param decorateSituation the value for b_apartment_new.decorateSituation
     *
     * @mbggenerated
     */
    public void setDecorateSituation(Integer decorateSituation) {
        this.decorateSituation = decorateSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.recommendReason
     *
     * @return the value of b_apartment_new.recommendReason
     *
     * @mbggenerated
     */
    public String getRecommendReason() {
        return recommendReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.recommendReason
     *
     * @param recommendReason the value for b_apartment_new.recommendReason
     *
     * @mbggenerated
     */
    public void setRecommendReason(String recommendReason) {
        this.recommendReason = recommendReason == null ? null : recommendReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.shelves
     *
     * @return the value of b_apartment_new.shelves
     *
     * @mbggenerated
     */
    public Integer getShelves() {
        return shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.shelves
     *
     * @param shelves the value for b_apartment_new.shelves
     *
     * @mbggenerated
     */
    public void setShelves(Integer shelves) {
        this.shelves = shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.createUser
     *
     * @return the value of b_apartment_new.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.createUser
     *
     * @param createUser the value for b_apartment_new.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.createTime
     *
     * @return the value of b_apartment_new.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.createTime
     *
     * @param createTime the value for b_apartment_new.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.updateUser
     *
     * @return the value of b_apartment_new.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.updateUser
     *
     * @param updateUser the value for b_apartment_new.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.updateTime
     *
     * @return the value of b_apartment_new.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.updateTime
     *
     * @param updateTime the value for b_apartment_new.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.deleteFlag
     *
     * @return the value of b_apartment_new.deleteFlag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.deleteFlag
     *
     * @param deleteFlag the value for b_apartment_new.deleteFlag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.averagePrice
     *
     * @return the value of b_apartment_new.averagePrice
     *
     * @mbggenerated
     */
    public String getAveragePrice() {
        return averagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.averagePrice
     *
     * @param averagePrice the value for b_apartment_new.averagePrice
     *
     * @mbggenerated
     */
    public void setAveragePrice(String averagePrice) {
        this.averagePrice = averagePrice == null ? null : averagePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.commissionCalMethod
     *
     * @return the value of b_apartment_new.commissionCalMethod
     *
     * @mbggenerated
     */
    public Integer getCommissionCalMethod() {
        return commissionCalMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.commissionCalMethod
     *
     * @param commissionCalMethod the value for b_apartment_new.commissionCalMethod
     *
     * @mbggenerated
     */
    public void setCommissionCalMethod(Integer commissionCalMethod) {
        this.commissionCalMethod = commissionCalMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_apartment_new.commissionValue
     *
     * @return the value of b_apartment_new.commissionValue
     *
     * @mbggenerated
     */
    public Float getCommissionValue() {
        return commissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_apartment_new.commissionValue
     *
     * @param commissionValue the value for b_apartment_new.commissionValue
     *
     * @mbggenerated
     */
    public void setCommissionValue(Float commissionValue) {
        this.commissionValue = commissionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApartmentNew other = (ApartmentNew) that;
        return (this.getApartmentId() == null ? other.getApartmentId() == null : this.getApartmentId().equals(other.getApartmentId()))
            && (this.getBuildingId() == null ? other.getBuildingId() == null : this.getBuildingId().equals(other.getBuildingId()))
            && (this.getBedroom() == null ? other.getBedroom() == null : this.getBedroom().equals(other.getBedroom()))
            && (this.getLivingRoom() == null ? other.getLivingRoom() == null : this.getLivingRoom().equals(other.getLivingRoom()))
            && (this.gettoltel() == null ? other.gettoltel() == null : this.gettoltel().equals(other.gettoltel()))
            && (this.getKitchen() == null ? other.getKitchen() == null : this.getKitchen().equals(other.getKitchen()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getMainApartment() == null ? other.getMainApartment() == null : this.getMainApartment().equals(other.getMainApartment()))
            && (this.getSaleNumber() == null ? other.getSaleNumber() == null : this.getSaleNumber().equals(other.getSaleNumber()))
            && (this.getAlreadySaleNumber() == null ? other.getAlreadySaleNumber() == null : this.getAlreadySaleNumber().equals(other.getAlreadySaleNumber()))
            && (this.getApartDiscount() == null ? other.getApartDiscount() == null : this.getApartDiscount().equals(other.getApartDiscount()))
            && (this.getOrientation() == null ? other.getOrientation() == null : this.getOrientation().equals(other.getOrientation()))
            && (this.getDecorateSituation() == null ? other.getDecorateSituation() == null : this.getDecorateSituation().equals(other.getDecorateSituation()))
            && (this.getRecommendReason() == null ? other.getRecommendReason() == null : this.getRecommendReason().equals(other.getRecommendReason()))
            && (this.getShelves() == null ? other.getShelves() == null : this.getShelves().equals(other.getShelves()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getAveragePrice() == null ? other.getAveragePrice() == null : this.getAveragePrice().equals(other.getAveragePrice()))
            && (this.getCommissionCalMethod() == null ? other.getCommissionCalMethod() == null : this.getCommissionCalMethod().equals(other.getCommissionCalMethod()))
            && (this.getCommissionValue() == null ? other.getCommissionValue() == null : this.getCommissionValue().equals(other.getCommissionValue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getApartmentId() == null) ? 0 : getApartmentId().hashCode());
        result = prime * result + ((getBuildingId() == null) ? 0 : getBuildingId().hashCode());
        result = prime * result + ((getBedroom() == null) ? 0 : getBedroom().hashCode());
        result = prime * result + ((getLivingRoom() == null) ? 0 : getLivingRoom().hashCode());
        result = prime * result + ((gettoltel() == null) ? 0 : gettoltel().hashCode());
        result = prime * result + ((getKitchen() == null) ? 0 : getKitchen().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getMainApartment() == null) ? 0 : getMainApartment().hashCode());
        result = prime * result + ((getSaleNumber() == null) ? 0 : getSaleNumber().hashCode());
        result = prime * result + ((getAlreadySaleNumber() == null) ? 0 : getAlreadySaleNumber().hashCode());
        result = prime * result + ((getApartDiscount() == null) ? 0 : getApartDiscount().hashCode());
        result = prime * result + ((getOrientation() == null) ? 0 : getOrientation().hashCode());
        result = prime * result + ((getDecorateSituation() == null) ? 0 : getDecorateSituation().hashCode());
        result = prime * result + ((getRecommendReason() == null) ? 0 : getRecommendReason().hashCode());
        result = prime * result + ((getShelves() == null) ? 0 : getShelves().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getAveragePrice() == null) ? 0 : getAveragePrice().hashCode());
        result = prime * result + ((getCommissionCalMethod() == null) ? 0 : getCommissionCalMethod().hashCode());
        result = prime * result + ((getCommissionValue() == null) ? 0 : getCommissionValue().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", apartmentId=").append(apartmentId);
        sb.append(", buildingId=").append(buildingId);
        sb.append(", bedroom=").append(bedroom);
        sb.append(", livingRoom=").append(livingRoom);
        sb.append(", toltel=").append(toltel);
        sb.append(", kitchen=").append(kitchen);
        sb.append(", area=").append(area);
        sb.append(", mainApartment=").append(mainApartment);
        sb.append(", saleNumber=").append(saleNumber);
        sb.append(", alreadySaleNumber=").append(alreadySaleNumber);
        sb.append(", apartDiscount=").append(apartDiscount);
        sb.append(", orientation=").append(orientation);
        sb.append(", decorateSituation=").append(decorateSituation);
        sb.append(", recommendReason=").append(recommendReason);
        sb.append(", shelves=").append(shelves);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", averagePrice=").append(averagePrice);
        sb.append(", commissionCalMethod=").append(commissionCalMethod);
        sb.append(", commissionValue=").append(commissionValue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}