package com.fei.bean;

import java.io.Serializable;
import java.util.Date;

public class AppsHis implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.appsHistoryId
     *
     * @mbggenerated
     */
    private String appsHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.appsId
     *
     * @mbggenerated
     */
    private String appsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.appsName
     *
     * @mbggenerated
     */
    private String appsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.systemType
     *
     * @mbggenerated
     */
    private String systemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.fileName
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.imgName
     *
     * @mbggenerated
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.imgFilePath
     *
     * @mbggenerated
     */
    private String imgFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.filePath
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.appStatus
     *
     * @mbggenerated
     */
    private String appStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.deleteTime
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.deleteUser
     *
     * @mbggenerated
     */
    private String deleteUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.deleteFlag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_appshis.versionCode
     *
     * @mbggenerated
     */
    private Integer versionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_appshis
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.appsHistoryId
     *
     * @return the value of s_appshis.appsHistoryId
     *
     * @mbggenerated
     */
    public String getAppsHistoryId() {
        return appsHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.appsHistoryId
     *
     * @param appsHistoryId the value for s_appshis.appsHistoryId
     *
     * @mbggenerated
     */
    public void setAppsHistoryId(String appsHistoryId) {
        this.appsHistoryId = appsHistoryId == null ? null : appsHistoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.appsId
     *
     * @return the value of s_appshis.appsId
     *
     * @mbggenerated
     */
    public String getAppsId() {
        return appsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.appsId
     *
     * @param appsId the value for s_appshis.appsId
     *
     * @mbggenerated
     */
    public void setAppsId(String appsId) {
        this.appsId = appsId == null ? null : appsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.appsName
     *
     * @return the value of s_appshis.appsName
     *
     * @mbggenerated
     */
    public String getAppsName() {
        return appsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.appsName
     *
     * @param appsName the value for s_appshis.appsName
     *
     * @mbggenerated
     */
    public void setAppsName(String appsName) {
        this.appsName = appsName == null ? null : appsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.systemType
     *
     * @return the value of s_appshis.systemType
     *
     * @mbggenerated
     */
    public String getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.systemType
     *
     * @param systemType the value for s_appshis.systemType
     *
     * @mbggenerated
     */
    public void setSystemType(String systemType) {
        this.systemType = systemType == null ? null : systemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.fileName
     *
     * @return the value of s_appshis.fileName
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.fileName
     *
     * @param fileName the value for s_appshis.fileName
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.imgName
     *
     * @return the value of s_appshis.imgName
     *
     * @mbggenerated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.imgName
     *
     * @param imgName the value for s_appshis.imgName
     *
     * @mbggenerated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.imgFilePath
     *
     * @return the value of s_appshis.imgFilePath
     *
     * @mbggenerated
     */
    public String getImgFilePath() {
        return imgFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.imgFilePath
     *
     * @param imgFilePath the value for s_appshis.imgFilePath
     *
     * @mbggenerated
     */
    public void setImgFilePath(String imgFilePath) {
        this.imgFilePath = imgFilePath == null ? null : imgFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.filePath
     *
     * @return the value of s_appshis.filePath
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.filePath
     *
     * @param filePath the value for s_appshis.filePath
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.version
     *
     * @return the value of s_appshis.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.version
     *
     * @param version the value for s_appshis.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.appStatus
     *
     * @return the value of s_appshis.appStatus
     *
     * @mbggenerated
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.appStatus
     *
     * @param appStatus the value for s_appshis.appStatus
     *
     * @mbggenerated
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.createUser
     *
     * @return the value of s_appshis.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.createUser
     *
     * @param createUser the value for s_appshis.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.createTime
     *
     * @return the value of s_appshis.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.createTime
     *
     * @param createTime the value for s_appshis.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.updateUser
     *
     * @return the value of s_appshis.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.updateUser
     *
     * @param updateUser the value for s_appshis.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.updateTime
     *
     * @return the value of s_appshis.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.updateTime
     *
     * @param updateTime the value for s_appshis.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.deleteTime
     *
     * @return the value of s_appshis.deleteTime
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.deleteTime
     *
     * @param deleteTime the value for s_appshis.deleteTime
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.deleteUser
     *
     * @return the value of s_appshis.deleteUser
     *
     * @mbggenerated
     */
    public String getDeleteUser() {
        return deleteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.deleteUser
     *
     * @param deleteUser the value for s_appshis.deleteUser
     *
     * @mbggenerated
     */
    public void setDeleteUser(String deleteUser) {
        this.deleteUser = deleteUser == null ? null : deleteUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.deleteFlag
     *
     * @return the value of s_appshis.deleteFlag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.deleteFlag
     *
     * @param deleteFlag the value for s_appshis.deleteFlag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_appshis.versionCode
     *
     * @return the value of s_appshis.versionCode
     *
     * @mbggenerated
     */
    public Integer getVersionCode() {
        return versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_appshis.versionCode
     *
     * @param versionCode the value for s_appshis.versionCode
     *
     * @mbggenerated
     */
    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_appshis
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppsHis other = (AppsHis) that;
        return (this.getAppsHistoryId() == null ? other.getAppsHistoryId() == null : this.getAppsHistoryId().equals(other.getAppsHistoryId()))
            && (this.getAppsId() == null ? other.getAppsId() == null : this.getAppsId().equals(other.getAppsId()))
            && (this.getAppsName() == null ? other.getAppsName() == null : this.getAppsName().equals(other.getAppsName()))
            && (this.getSystemType() == null ? other.getSystemType() == null : this.getSystemType().equals(other.getSystemType()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getImgName() == null ? other.getImgName() == null : this.getImgName().equals(other.getImgName()))
            && (this.getImgFilePath() == null ? other.getImgFilePath() == null : this.getImgFilePath().equals(other.getImgFilePath()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getVersion() == null ? other.getVersion() == null : this.getVersion().equals(other.getVersion()))
            && (this.getAppStatus() == null ? other.getAppStatus() == null : this.getAppStatus().equals(other.getAppStatus()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()))
            && (this.getDeleteUser() == null ? other.getDeleteUser() == null : this.getDeleteUser().equals(other.getDeleteUser()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()))
            && (this.getVersionCode() == null ? other.getVersionCode() == null : this.getVersionCode().equals(other.getVersionCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_appshis
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppsHistoryId() == null) ? 0 : getAppsHistoryId().hashCode());
        result = prime * result + ((getAppsId() == null) ? 0 : getAppsId().hashCode());
        result = prime * result + ((getAppsName() == null) ? 0 : getAppsName().hashCode());
        result = prime * result + ((getSystemType() == null) ? 0 : getSystemType().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getImgName() == null) ? 0 : getImgName().hashCode());
        result = prime * result + ((getImgFilePath() == null) ? 0 : getImgFilePath().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getAppStatus() == null) ? 0 : getAppStatus().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        result = prime * result + ((getDeleteUser() == null) ? 0 : getDeleteUser().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        result = prime * result + ((getVersionCode() == null) ? 0 : getVersionCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_appshis
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appsHistoryId=").append(appsHistoryId);
        sb.append(", appsId=").append(appsId);
        sb.append(", appsName=").append(appsName);
        sb.append(", systemType=").append(systemType);
        sb.append(", fileName=").append(fileName);
        sb.append(", imgName=").append(imgName);
        sb.append(", imgFilePath=").append(imgFilePath);
        sb.append(", filePath=").append(filePath);
        sb.append(", version=").append(version);
        sb.append(", appStatus=").append(appStatus);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", deleteUser=").append(deleteUser);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", versionCode=").append(versionCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}