package com.fei.bean;

import java.io.Serializable;

public class Area implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.areaid
     *
     * @mbggenerated
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.areacode
     *
     * @mbggenerated
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.areaname
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.arealeval
     *
     * @mbggenerated
     */
    private String arealeval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.parentcode
     *
     * @mbggenerated
     */
    private String parentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.firstalpha
     *
     * @mbggenerated
     */
    private String firstalpha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_area.areadesc
     *
     * @mbggenerated
     */
    private String areadesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_area
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.areaid
     *
     * @return the value of s_area.areaid
     *
     * @mbggenerated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.areaid
     *
     * @param areaid the value for s_area.areaid
     *
     * @mbggenerated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.areacode
     *
     * @return the value of s_area.areacode
     *
     * @mbggenerated
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.areacode
     *
     * @param areacode the value for s_area.areacode
     *
     * @mbggenerated
     */
    public void setAreacode(Integer areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.areaname
     *
     * @return the value of s_area.areaname
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.areaname
     *
     * @param areaname the value for s_area.areaname
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.arealeval
     *
     * @return the value of s_area.arealeval
     *
     * @mbggenerated
     */
    public String getArealeval() {
        return arealeval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.arealeval
     *
     * @param arealeval the value for s_area.arealeval
     *
     * @mbggenerated
     */
    public void setArealeval(String arealeval) {
        this.arealeval = arealeval == null ? null : arealeval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.parentcode
     *
     * @return the value of s_area.parentcode
     *
     * @mbggenerated
     */
    public String getParentcode() {
        return parentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.parentcode
     *
     * @param parentcode the value for s_area.parentcode
     *
     * @mbggenerated
     */
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode == null ? null : parentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.pinyin
     *
     * @return the value of s_area.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.pinyin
     *
     * @param pinyin the value for s_area.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.firstalpha
     *
     * @return the value of s_area.firstalpha
     *
     * @mbggenerated
     */
    public String getFirstalpha() {
        return firstalpha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.firstalpha
     *
     * @param firstalpha the value for s_area.firstalpha
     *
     * @mbggenerated
     */
    public void setFirstalpha(String firstalpha) {
        this.firstalpha = firstalpha == null ? null : firstalpha.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_area.areadesc
     *
     * @return the value of s_area.areadesc
     *
     * @mbggenerated
     */
    public String getAreadesc() {
        return areadesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_area.areadesc
     *
     * @param areadesc the value for s_area.areadesc
     *
     * @mbggenerated
     */
    public void setAreadesc(String areadesc) {
        this.areadesc = areadesc == null ? null : areadesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_area
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Area other = (Area) that;
        return (this.getAreaid() == null ? other.getAreaid() == null : this.getAreaid().equals(other.getAreaid()))
            && (this.getAreacode() == null ? other.getAreacode() == null : this.getAreacode().equals(other.getAreacode()))
            && (this.getAreaname() == null ? other.getAreaname() == null : this.getAreaname().equals(other.getAreaname()))
            && (this.getArealeval() == null ? other.getArealeval() == null : this.getArealeval().equals(other.getArealeval()))
            && (this.getParentcode() == null ? other.getParentcode() == null : this.getParentcode().equals(other.getParentcode()))
            && (this.getPinyin() == null ? other.getPinyin() == null : this.getPinyin().equals(other.getPinyin()))
            && (this.getFirstalpha() == null ? other.getFirstalpha() == null : this.getFirstalpha().equals(other.getFirstalpha()))
            && (this.getAreadesc() == null ? other.getAreadesc() == null : this.getAreadesc().equals(other.getAreadesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_area
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAreaid() == null) ? 0 : getAreaid().hashCode());
        result = prime * result + ((getAreacode() == null) ? 0 : getAreacode().hashCode());
        result = prime * result + ((getAreaname() == null) ? 0 : getAreaname().hashCode());
        result = prime * result + ((getArealeval() == null) ? 0 : getArealeval().hashCode());
        result = prime * result + ((getParentcode() == null) ? 0 : getParentcode().hashCode());
        result = prime * result + ((getPinyin() == null) ? 0 : getPinyin().hashCode());
        result = prime * result + ((getFirstalpha() == null) ? 0 : getFirstalpha().hashCode());
        result = prime * result + ((getAreadesc() == null) ? 0 : getAreadesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_area
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areaid=").append(areaid);
        sb.append(", areacode=").append(areacode);
        sb.append(", areaname=").append(areaname);
        sb.append(", arealeval=").append(arealeval);
        sb.append(", parentcode=").append(parentcode);
        sb.append(", pinyin=").append(pinyin);
        sb.append(", firstalpha=").append(firstalpha);
        sb.append(", areadesc=").append(areadesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}