package com.fei.bean;

import java.io.Serializable;
import java.util.Date;

public class BuildingFile implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.buildingFileId
     *
     * @mbggenerated
     */
    private String buildingFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.buildingId
     *
     * @mbggenerated
     */
    private String buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.filePath
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.isThumbnail
     *
     * @mbggenerated
     */
    private Integer isThumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_buildingfile.deleteFlag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_buildingfile
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.buildingFileId
     *
     * @return the value of b_buildingfile.buildingFileId
     *
     * @mbggenerated
     */
    public String getBuildingFileId() {
        return buildingFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.buildingFileId
     *
     * @param buildingFileId the value for b_buildingfile.buildingFileId
     *
     * @mbggenerated
     */
    public void setBuildingFileId(String buildingFileId) {
        this.buildingFileId = buildingFileId == null ? null : buildingFileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.buildingId
     *
     * @return the value of b_buildingfile.buildingId
     *
     * @mbggenerated
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.buildingId
     *
     * @param buildingId the value for b_buildingfile.buildingId
     *
     * @mbggenerated
     */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId == null ? null : buildingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.filePath
     *
     * @return the value of b_buildingfile.filePath
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.filePath
     *
     * @param filePath the value for b_buildingfile.filePath
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.isThumbnail
     *
     * @return the value of b_buildingfile.isThumbnail
     *
     * @mbggenerated
     */
    public Integer getIsThumbnail() {
        return isThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.isThumbnail
     *
     * @param isThumbnail the value for b_buildingfile.isThumbnail
     *
     * @mbggenerated
     */
    public void setIsThumbnail(Integer isThumbnail) {
        this.isThumbnail = isThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.createUser
     *
     * @return the value of b_buildingfile.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.createUser
     *
     * @param createUser the value for b_buildingfile.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.createTime
     *
     * @return the value of b_buildingfile.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.createTime
     *
     * @param createTime the value for b_buildingfile.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.updateUser
     *
     * @return the value of b_buildingfile.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.updateUser
     *
     * @param updateUser the value for b_buildingfile.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.updateTime
     *
     * @return the value of b_buildingfile.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.updateTime
     *
     * @param updateTime the value for b_buildingfile.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_buildingfile.deleteFlag
     *
     * @return the value of b_buildingfile.deleteFlag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_buildingfile.deleteFlag
     *
     * @param deleteFlag the value for b_buildingfile.deleteFlag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buildingfile
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BuildingFile other = (BuildingFile) that;
        return (this.getBuildingFileId() == null ? other.getBuildingFileId() == null : this.getBuildingFileId().equals(other.getBuildingFileId()))
            && (this.getBuildingId() == null ? other.getBuildingId() == null : this.getBuildingId().equals(other.getBuildingId()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getIsThumbnail() == null ? other.getIsThumbnail() == null : this.getIsThumbnail().equals(other.getIsThumbnail()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buildingfile
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBuildingFileId() == null) ? 0 : getBuildingFileId().hashCode());
        result = prime * result + ((getBuildingId() == null) ? 0 : getBuildingId().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getIsThumbnail() == null) ? 0 : getIsThumbnail().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_buildingfile
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingFileId=").append(buildingFileId);
        sb.append(", buildingId=").append(buildingId);
        sb.append(", filePath=").append(filePath);
        sb.append(", isThumbnail=").append(isThumbnail);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}