package com.fei.bean;

import java.io.Serializable;
import java.util.Date;

public class Building implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.buildingId
     *
     * @mbggenerated
     */
    private String buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.buildingName
     *
     * @mbggenerated
     */
    private String buildingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.isTop
     *
     * @mbggenerated
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.topEndTime
     *
     * @mbggenerated
     */
    private Date topEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.promoteRules
     *
     * @mbggenerated
     */
    private String promoteRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.valuePoint
     *
     * @mbggenerated
     */
    private String valuePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.saleDynamic
     *
     * @mbggenerated
     */
    private String saleDynamic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.areaId
     *
     * @mbggenerated
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.cityId
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.zoneId
     *
     * @mbggenerated
     */
    private String zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.detailAddress
     *
     * @mbggenerated
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.developers
     *
     * @mbggenerated
     */
    private String developers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.propertyCompany
     *
     * @mbggenerated
     */
    private String propertyCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.coversArea
     *
     * @mbggenerated
     */
    private String coversArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.buildingArea
     *
     * @mbggenerated
     */
    private String buildingArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.totalHosing
     *
     * @mbggenerated
     */
    private String totalHosing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.plotRatio
     *
     * @mbggenerated
     */
    private String plotRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.greenRate
     *
     * @mbggenerated
     */
    private String greenRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.propertyCost
     *
     * @mbggenerated
     */
    private String propertyCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.decorateSituation
     *
     * @mbggenerated
     */
    private Integer decorateSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.averagePrice
     *
     * @mbggenerated
     */
    private String averagePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.elevatorProportion
     *
     * @mbggenerated
     */
    private String elevatorProportion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.businessArea
     *
     * @mbggenerated
     */
    private String businessArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.parkingNumber
     *
     * @mbggenerated
     */
    private Integer parkingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.garageNumber
     *
     * @mbggenerated
     */
    private Integer garageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.operatorName
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.operatorPhone
     *
     * @mbggenerated
     */
    private String operatorPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.lifeCompanion
     *
     * @mbggenerated
     */
    private String lifeCompanion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.schoolCompanion
     *
     * @mbggenerated
     */
    private String schoolCompanion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.trafficTravel
     *
     * @mbggenerated
     */
    private String trafficTravel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.buildingType
     *
     * @mbggenerated
     */
    private Integer buildingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.consultantId
     *
     * @mbggenerated
     */
    private String consultantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.commissionInfo
     *
     * @mbggenerated
     */
    private String commissionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.reportRules
     *
     * @mbggenerated
     */
    private String reportRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.lookRules
     *
     * @mbggenerated
     */
    private String lookRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.dealRules
     *
     * @mbggenerated
     */
    private String dealRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.soluteRules
     *
     * @mbggenerated
     */
    private String soluteRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.othersRules
     *
     * @mbggenerated
     */
    private String othersRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.shelves
     *
     * @mbggenerated
     */
    private Integer shelves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.travelProperty
     *
     * @mbggenerated
     */
    private Integer travelProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.subwayLine
     *
     * @mbggenerated
     */
    private String subwayLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building.deleteFlag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_building
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.buildingId
     *
     * @return the value of b_building.buildingId
     *
     * @mbggenerated
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.buildingId
     *
     * @param buildingId the value for b_building.buildingId
     *
     * @mbggenerated
     */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId == null ? null : buildingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.buildingName
     *
     * @return the value of b_building.buildingName
     *
     * @mbggenerated
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.buildingName
     *
     * @param buildingName the value for b_building.buildingName
     *
     * @mbggenerated
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.isTop
     *
     * @return the value of b_building.isTop
     *
     * @mbggenerated
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.isTop
     *
     * @param isTop the value for b_building.isTop
     *
     * @mbggenerated
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.topEndTime
     *
     * @return the value of b_building.topEndTime
     *
     * @mbggenerated
     */
    public Date getTopEndTime() {
        return topEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.topEndTime
     *
     * @param topEndTime the value for b_building.topEndTime
     *
     * @mbggenerated
     */
    public void setTopEndTime(Date topEndTime) {
        this.topEndTime = topEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.promoteRules
     *
     * @return the value of b_building.promoteRules
     *
     * @mbggenerated
     */
    public String getPromoteRules() {
        return promoteRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.promoteRules
     *
     * @param promoteRules the value for b_building.promoteRules
     *
     * @mbggenerated
     */
    public void setPromoteRules(String promoteRules) {
        this.promoteRules = promoteRules == null ? null : promoteRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.valuePoint
     *
     * @return the value of b_building.valuePoint
     *
     * @mbggenerated
     */
    public String getValuePoint() {
        return valuePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.valuePoint
     *
     * @param valuePoint the value for b_building.valuePoint
     *
     * @mbggenerated
     */
    public void setValuePoint(String valuePoint) {
        this.valuePoint = valuePoint == null ? null : valuePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.saleDynamic
     *
     * @return the value of b_building.saleDynamic
     *
     * @mbggenerated
     */
    public String getSaleDynamic() {
        return saleDynamic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.saleDynamic
     *
     * @param saleDynamic the value for b_building.saleDynamic
     *
     * @mbggenerated
     */
    public void setSaleDynamic(String saleDynamic) {
        this.saleDynamic = saleDynamic == null ? null : saleDynamic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.areaId
     *
     * @return the value of b_building.areaId
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.areaId
     *
     * @param areaId the value for b_building.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.cityId
     *
     * @return the value of b_building.cityId
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.cityId
     *
     * @param cityId the value for b_building.cityId
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.zoneId
     *
     * @return the value of b_building.zoneId
     *
     * @mbggenerated
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.zoneId
     *
     * @param zoneId the value for b_building.zoneId
     *
     * @mbggenerated
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId == null ? null : zoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.detailAddress
     *
     * @return the value of b_building.detailAddress
     *
     * @mbggenerated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.detailAddress
     *
     * @param detailAddress the value for b_building.detailAddress
     *
     * @mbggenerated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.longitude
     *
     * @return the value of b_building.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.longitude
     *
     * @param longitude the value for b_building.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.latitude
     *
     * @return the value of b_building.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.latitude
     *
     * @param latitude the value for b_building.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.developers
     *
     * @return the value of b_building.developers
     *
     * @mbggenerated
     */
    public String getDevelopers() {
        return developers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.developers
     *
     * @param developers the value for b_building.developers
     *
     * @mbggenerated
     */
    public void setDevelopers(String developers) {
        this.developers = developers == null ? null : developers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.propertyCompany
     *
     * @return the value of b_building.propertyCompany
     *
     * @mbggenerated
     */
    public String getPropertyCompany() {
        return propertyCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.propertyCompany
     *
     * @param propertyCompany the value for b_building.propertyCompany
     *
     * @mbggenerated
     */
    public void setPropertyCompany(String propertyCompany) {
        this.propertyCompany = propertyCompany == null ? null : propertyCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.coversArea
     *
     * @return the value of b_building.coversArea
     *
     * @mbggenerated
     */
    public String getCoversArea() {
        return coversArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.coversArea
     *
     * @param coversArea the value for b_building.coversArea
     *
     * @mbggenerated
     */
    public void setCoversArea(String coversArea) {
        this.coversArea = coversArea == null ? null : coversArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.buildingArea
     *
     * @return the value of b_building.buildingArea
     *
     * @mbggenerated
     */
    public String getBuildingArea() {
        return buildingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.buildingArea
     *
     * @param buildingArea the value for b_building.buildingArea
     *
     * @mbggenerated
     */
    public void setBuildingArea(String buildingArea) {
        this.buildingArea = buildingArea == null ? null : buildingArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.totalHosing
     *
     * @return the value of b_building.totalHosing
     *
     * @mbggenerated
     */
    public String getTotalHosing() {
        return totalHosing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.totalHosing
     *
     * @param totalHosing the value for b_building.totalHosing
     *
     * @mbggenerated
     */
    public void setTotalHosing(String totalHosing) {
        this.totalHosing = totalHosing == null ? null : totalHosing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.plotRatio
     *
     * @return the value of b_building.plotRatio
     *
     * @mbggenerated
     */
    public String getPlotRatio() {
        return plotRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.plotRatio
     *
     * @param plotRatio the value for b_building.plotRatio
     *
     * @mbggenerated
     */
    public void setPlotRatio(String plotRatio) {
        this.plotRatio = plotRatio == null ? null : plotRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.greenRate
     *
     * @return the value of b_building.greenRate
     *
     * @mbggenerated
     */
    public String getGreenRate() {
        return greenRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.greenRate
     *
     * @param greenRate the value for b_building.greenRate
     *
     * @mbggenerated
     */
    public void setGreenRate(String greenRate) {
        this.greenRate = greenRate == null ? null : greenRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.propertyCost
     *
     * @return the value of b_building.propertyCost
     *
     * @mbggenerated
     */
    public String getPropertyCost() {
        return propertyCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.propertyCost
     *
     * @param propertyCost the value for b_building.propertyCost
     *
     * @mbggenerated
     */
    public void setPropertyCost(String propertyCost) {
        this.propertyCost = propertyCost == null ? null : propertyCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.decorateSituation
     *
     * @return the value of b_building.decorateSituation
     *
     * @mbggenerated
     */
    public Integer getDecorateSituation() {
        return decorateSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.decorateSituation
     *
     * @param decorateSituation the value for b_building.decorateSituation
     *
     * @mbggenerated
     */
    public void setDecorateSituation(Integer decorateSituation) {
        this.decorateSituation = decorateSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.averagePrice
     *
     * @return the value of b_building.averagePrice
     *
     * @mbggenerated
     */
    public String getAveragePrice() {
        return averagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.averagePrice
     *
     * @param averagePrice the value for b_building.averagePrice
     *
     * @mbggenerated
     */
    public void setAveragePrice(String averagePrice) {
        this.averagePrice = averagePrice == null ? null : averagePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.elevatorProportion
     *
     * @return the value of b_building.elevatorProportion
     *
     * @mbggenerated
     */
    public String getElevatorProportion() {
        return elevatorProportion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.elevatorProportion
     *
     * @param elevatorProportion the value for b_building.elevatorProportion
     *
     * @mbggenerated
     */
    public void setElevatorProportion(String elevatorProportion) {
        this.elevatorProportion = elevatorProportion == null ? null : elevatorProportion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.businessArea
     *
     * @return the value of b_building.businessArea
     *
     * @mbggenerated
     */
    public String getBusinessArea() {
        return businessArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.businessArea
     *
     * @param businessArea the value for b_building.businessArea
     *
     * @mbggenerated
     */
    public void setBusinessArea(String businessArea) {
        this.businessArea = businessArea == null ? null : businessArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.parkingNumber
     *
     * @return the value of b_building.parkingNumber
     *
     * @mbggenerated
     */
    public Integer getParkingNumber() {
        return parkingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.parkingNumber
     *
     * @param parkingNumber the value for b_building.parkingNumber
     *
     * @mbggenerated
     */
    public void setParkingNumber(Integer parkingNumber) {
        this.parkingNumber = parkingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.garageNumber
     *
     * @return the value of b_building.garageNumber
     *
     * @mbggenerated
     */
    public Integer getGarageNumber() {
        return garageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.garageNumber
     *
     * @param garageNumber the value for b_building.garageNumber
     *
     * @mbggenerated
     */
    public void setGarageNumber(Integer garageNumber) {
        this.garageNumber = garageNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.operatorName
     *
     * @return the value of b_building.operatorName
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.operatorName
     *
     * @param operatorName the value for b_building.operatorName
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.operatorPhone
     *
     * @return the value of b_building.operatorPhone
     *
     * @mbggenerated
     */
    public String getOperatorPhone() {
        return operatorPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.operatorPhone
     *
     * @param operatorPhone the value for b_building.operatorPhone
     *
     * @mbggenerated
     */
    public void setOperatorPhone(String operatorPhone) {
        this.operatorPhone = operatorPhone == null ? null : operatorPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.lifeCompanion
     *
     * @return the value of b_building.lifeCompanion
     *
     * @mbggenerated
     */
    public String getLifeCompanion() {
        return lifeCompanion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.lifeCompanion
     *
     * @param lifeCompanion the value for b_building.lifeCompanion
     *
     * @mbggenerated
     */
    public void setLifeCompanion(String lifeCompanion) {
        this.lifeCompanion = lifeCompanion == null ? null : lifeCompanion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.schoolCompanion
     *
     * @return the value of b_building.schoolCompanion
     *
     * @mbggenerated
     */
    public String getSchoolCompanion() {
        return schoolCompanion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.schoolCompanion
     *
     * @param schoolCompanion the value for b_building.schoolCompanion
     *
     * @mbggenerated
     */
    public void setSchoolCompanion(String schoolCompanion) {
        this.schoolCompanion = schoolCompanion == null ? null : schoolCompanion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.trafficTravel
     *
     * @return the value of b_building.trafficTravel
     *
     * @mbggenerated
     */
    public String getTrafficTravel() {
        return trafficTravel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.trafficTravel
     *
     * @param trafficTravel the value for b_building.trafficTravel
     *
     * @mbggenerated
     */
    public void setTrafficTravel(String trafficTravel) {
        this.trafficTravel = trafficTravel == null ? null : trafficTravel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.buildingType
     *
     * @return the value of b_building.buildingType
     *
     * @mbggenerated
     */
    public Integer getBuildingType() {
        return buildingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.buildingType
     *
     * @param buildingType the value for b_building.buildingType
     *
     * @mbggenerated
     */
    public void setBuildingType(Integer buildingType) {
        this.buildingType = buildingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.consultantId
     *
     * @return the value of b_building.consultantId
     *
     * @mbggenerated
     */
    public String getConsultantId() {
        return consultantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.consultantId
     *
     * @param consultantId the value for b_building.consultantId
     *
     * @mbggenerated
     */
    public void setConsultantId(String consultantId) {
        this.consultantId = consultantId == null ? null : consultantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.commissionInfo
     *
     * @return the value of b_building.commissionInfo
     *
     * @mbggenerated
     */
    public String getCommissionInfo() {
        return commissionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.commissionInfo
     *
     * @param commissionInfo the value for b_building.commissionInfo
     *
     * @mbggenerated
     */
    public void setCommissionInfo(String commissionInfo) {
        this.commissionInfo = commissionInfo == null ? null : commissionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.reportRules
     *
     * @return the value of b_building.reportRules
     *
     * @mbggenerated
     */
    public String getReportRules() {
        return reportRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.reportRules
     *
     * @param reportRules the value for b_building.reportRules
     *
     * @mbggenerated
     */
    public void setReportRules(String reportRules) {
        this.reportRules = reportRules == null ? null : reportRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.lookRules
     *
     * @return the value of b_building.lookRules
     *
     * @mbggenerated
     */
    public String getLookRules() {
        return lookRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.lookRules
     *
     * @param lookRules the value for b_building.lookRules
     *
     * @mbggenerated
     */
    public void setLookRules(String lookRules) {
        this.lookRules = lookRules == null ? null : lookRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.dealRules
     *
     * @return the value of b_building.dealRules
     *
     * @mbggenerated
     */
    public String getDealRules() {
        return dealRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.dealRules
     *
     * @param dealRules the value for b_building.dealRules
     *
     * @mbggenerated
     */
    public void setDealRules(String dealRules) {
        this.dealRules = dealRules == null ? null : dealRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.soluteRules
     *
     * @return the value of b_building.soluteRules
     *
     * @mbggenerated
     */
    public String getSoluteRules() {
        return soluteRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.soluteRules
     *
     * @param soluteRules the value for b_building.soluteRules
     *
     * @mbggenerated
     */
    public void setSoluteRules(String soluteRules) {
        this.soluteRules = soluteRules == null ? null : soluteRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.othersRules
     *
     * @return the value of b_building.othersRules
     *
     * @mbggenerated
     */
    public String getOthersRules() {
        return othersRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.othersRules
     *
     * @param othersRules the value for b_building.othersRules
     *
     * @mbggenerated
     */
    public void setOthersRules(String othersRules) {
        this.othersRules = othersRules == null ? null : othersRules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.shelves
     *
     * @return the value of b_building.shelves
     *
     * @mbggenerated
     */
    public Integer getShelves() {
        return shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.shelves
     *
     * @param shelves the value for b_building.shelves
     *
     * @mbggenerated
     */
    public void setShelves(Integer shelves) {
        this.shelves = shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.travelProperty
     *
     * @return the value of b_building.travelProperty
     *
     * @mbggenerated
     */
    public Integer getTravelProperty() {
        return travelProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.travelProperty
     *
     * @param travelProperty the value for b_building.travelProperty
     *
     * @mbggenerated
     */
    public void setTravelProperty(Integer travelProperty) {
        this.travelProperty = travelProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.subwayLine
     *
     * @return the value of b_building.subwayLine
     *
     * @mbggenerated
     */
    public String getSubwayLine() {
        return subwayLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.subwayLine
     *
     * @param subwayLine the value for b_building.subwayLine
     *
     * @mbggenerated
     */
    public void setSubwayLine(String subwayLine) {
        this.subwayLine = subwayLine == null ? null : subwayLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.createUser
     *
     * @return the value of b_building.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.createUser
     *
     * @param createUser the value for b_building.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.createTime
     *
     * @return the value of b_building.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.createTime
     *
     * @param createTime the value for b_building.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.updateUser
     *
     * @return the value of b_building.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.updateUser
     *
     * @param updateUser the value for b_building.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.updateTime
     *
     * @return the value of b_building.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.updateTime
     *
     * @param updateTime the value for b_building.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building.deleteFlag
     *
     * @return the value of b_building.deleteFlag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building.deleteFlag
     *
     * @param deleteFlag the value for b_building.deleteFlag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_building
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Building other = (Building) that;
        return (this.getBuildingId() == null ? other.getBuildingId() == null : this.getBuildingId().equals(other.getBuildingId()))
            && (this.getBuildingName() == null ? other.getBuildingName() == null : this.getBuildingName().equals(other.getBuildingName()))
            && (this.getIsTop() == null ? other.getIsTop() == null : this.getIsTop().equals(other.getIsTop()))
            && (this.getTopEndTime() == null ? other.getTopEndTime() == null : this.getTopEndTime().equals(other.getTopEndTime()))
            && (this.getPromoteRules() == null ? other.getPromoteRules() == null : this.getPromoteRules().equals(other.getPromoteRules()))
            && (this.getValuePoint() == null ? other.getValuePoint() == null : this.getValuePoint().equals(other.getValuePoint()))
            && (this.getSaleDynamic() == null ? other.getSaleDynamic() == null : this.getSaleDynamic().equals(other.getSaleDynamic()))
            && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getZoneId() == null ? other.getZoneId() == null : this.getZoneId().equals(other.getZoneId()))
            && (this.getDetailAddress() == null ? other.getDetailAddress() == null : this.getDetailAddress().equals(other.getDetailAddress()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getDevelopers() == null ? other.getDevelopers() == null : this.getDevelopers().equals(other.getDevelopers()))
            && (this.getPropertyCompany() == null ? other.getPropertyCompany() == null : this.getPropertyCompany().equals(other.getPropertyCompany()))
            && (this.getCoversArea() == null ? other.getCoversArea() == null : this.getCoversArea().equals(other.getCoversArea()))
            && (this.getBuildingArea() == null ? other.getBuildingArea() == null : this.getBuildingArea().equals(other.getBuildingArea()))
            && (this.getTotalHosing() == null ? other.getTotalHosing() == null : this.getTotalHosing().equals(other.getTotalHosing()))
            && (this.getPlotRatio() == null ? other.getPlotRatio() == null : this.getPlotRatio().equals(other.getPlotRatio()))
            && (this.getGreenRate() == null ? other.getGreenRate() == null : this.getGreenRate().equals(other.getGreenRate()))
            && (this.getPropertyCost() == null ? other.getPropertyCost() == null : this.getPropertyCost().equals(other.getPropertyCost()))
            && (this.getDecorateSituation() == null ? other.getDecorateSituation() == null : this.getDecorateSituation().equals(other.getDecorateSituation()))
            && (this.getAveragePrice() == null ? other.getAveragePrice() == null : this.getAveragePrice().equals(other.getAveragePrice()))
            && (this.getElevatorProportion() == null ? other.getElevatorProportion() == null : this.getElevatorProportion().equals(other.getElevatorProportion()))
            && (this.getBusinessArea() == null ? other.getBusinessArea() == null : this.getBusinessArea().equals(other.getBusinessArea()))
            && (this.getParkingNumber() == null ? other.getParkingNumber() == null : this.getParkingNumber().equals(other.getParkingNumber()))
            && (this.getGarageNumber() == null ? other.getGarageNumber() == null : this.getGarageNumber().equals(other.getGarageNumber()))
            && (this.getOperatorName() == null ? other.getOperatorName() == null : this.getOperatorName().equals(other.getOperatorName()))
            && (this.getOperatorPhone() == null ? other.getOperatorPhone() == null : this.getOperatorPhone().equals(other.getOperatorPhone()))
            && (this.getLifeCompanion() == null ? other.getLifeCompanion() == null : this.getLifeCompanion().equals(other.getLifeCompanion()))
            && (this.getSchoolCompanion() == null ? other.getSchoolCompanion() == null : this.getSchoolCompanion().equals(other.getSchoolCompanion()))
            && (this.getTrafficTravel() == null ? other.getTrafficTravel() == null : this.getTrafficTravel().equals(other.getTrafficTravel()))
            && (this.getBuildingType() == null ? other.getBuildingType() == null : this.getBuildingType().equals(other.getBuildingType()))
            && (this.getConsultantId() == null ? other.getConsultantId() == null : this.getConsultantId().equals(other.getConsultantId()))
            && (this.getCommissionInfo() == null ? other.getCommissionInfo() == null : this.getCommissionInfo().equals(other.getCommissionInfo()))
            && (this.getReportRules() == null ? other.getReportRules() == null : this.getReportRules().equals(other.getReportRules()))
            && (this.getLookRules() == null ? other.getLookRules() == null : this.getLookRules().equals(other.getLookRules()))
            && (this.getDealRules() == null ? other.getDealRules() == null : this.getDealRules().equals(other.getDealRules()))
            && (this.getSoluteRules() == null ? other.getSoluteRules() == null : this.getSoluteRules().equals(other.getSoluteRules()))
            && (this.getOthersRules() == null ? other.getOthersRules() == null : this.getOthersRules().equals(other.getOthersRules()))
            && (this.getShelves() == null ? other.getShelves() == null : this.getShelves().equals(other.getShelves()))
            && (this.getTravelProperty() == null ? other.getTravelProperty() == null : this.getTravelProperty().equals(other.getTravelProperty()))
            && (this.getSubwayLine() == null ? other.getSubwayLine() == null : this.getSubwayLine().equals(other.getSubwayLine()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_building
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBuildingId() == null) ? 0 : getBuildingId().hashCode());
        result = prime * result + ((getBuildingName() == null) ? 0 : getBuildingName().hashCode());
        result = prime * result + ((getIsTop() == null) ? 0 : getIsTop().hashCode());
        result = prime * result + ((getTopEndTime() == null) ? 0 : getTopEndTime().hashCode());
        result = prime * result + ((getPromoteRules() == null) ? 0 : getPromoteRules().hashCode());
        result = prime * result + ((getValuePoint() == null) ? 0 : getValuePoint().hashCode());
        result = prime * result + ((getSaleDynamic() == null) ? 0 : getSaleDynamic().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getZoneId() == null) ? 0 : getZoneId().hashCode());
        result = prime * result + ((getDetailAddress() == null) ? 0 : getDetailAddress().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getDevelopers() == null) ? 0 : getDevelopers().hashCode());
        result = prime * result + ((getPropertyCompany() == null) ? 0 : getPropertyCompany().hashCode());
        result = prime * result + ((getCoversArea() == null) ? 0 : getCoversArea().hashCode());
        result = prime * result + ((getBuildingArea() == null) ? 0 : getBuildingArea().hashCode());
        result = prime * result + ((getTotalHosing() == null) ? 0 : getTotalHosing().hashCode());
        result = prime * result + ((getPlotRatio() == null) ? 0 : getPlotRatio().hashCode());
        result = prime * result + ((getGreenRate() == null) ? 0 : getGreenRate().hashCode());
        result = prime * result + ((getPropertyCost() == null) ? 0 : getPropertyCost().hashCode());
        result = prime * result + ((getDecorateSituation() == null) ? 0 : getDecorateSituation().hashCode());
        result = prime * result + ((getAveragePrice() == null) ? 0 : getAveragePrice().hashCode());
        result = prime * result + ((getElevatorProportion() == null) ? 0 : getElevatorProportion().hashCode());
        result = prime * result + ((getBusinessArea() == null) ? 0 : getBusinessArea().hashCode());
        result = prime * result + ((getParkingNumber() == null) ? 0 : getParkingNumber().hashCode());
        result = prime * result + ((getGarageNumber() == null) ? 0 : getGarageNumber().hashCode());
        result = prime * result + ((getOperatorName() == null) ? 0 : getOperatorName().hashCode());
        result = prime * result + ((getOperatorPhone() == null) ? 0 : getOperatorPhone().hashCode());
        result = prime * result + ((getLifeCompanion() == null) ? 0 : getLifeCompanion().hashCode());
        result = prime * result + ((getSchoolCompanion() == null) ? 0 : getSchoolCompanion().hashCode());
        result = prime * result + ((getTrafficTravel() == null) ? 0 : getTrafficTravel().hashCode());
        result = prime * result + ((getBuildingType() == null) ? 0 : getBuildingType().hashCode());
        result = prime * result + ((getConsultantId() == null) ? 0 : getConsultantId().hashCode());
        result = prime * result + ((getCommissionInfo() == null) ? 0 : getCommissionInfo().hashCode());
        result = prime * result + ((getReportRules() == null) ? 0 : getReportRules().hashCode());
        result = prime * result + ((getLookRules() == null) ? 0 : getLookRules().hashCode());
        result = prime * result + ((getDealRules() == null) ? 0 : getDealRules().hashCode());
        result = prime * result + ((getSoluteRules() == null) ? 0 : getSoluteRules().hashCode());
        result = prime * result + ((getOthersRules() == null) ? 0 : getOthersRules().hashCode());
        result = prime * result + ((getShelves() == null) ? 0 : getShelves().hashCode());
        result = prime * result + ((getTravelProperty() == null) ? 0 : getTravelProperty().hashCode());
        result = prime * result + ((getSubwayLine() == null) ? 0 : getSubwayLine().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_building
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingId=").append(buildingId);
        sb.append(", buildingName=").append(buildingName);
        sb.append(", isTop=").append(isTop);
        sb.append(", topEndTime=").append(topEndTime);
        sb.append(", promoteRules=").append(promoteRules);
        sb.append(", valuePoint=").append(valuePoint);
        sb.append(", saleDynamic=").append(saleDynamic);
        sb.append(", areaId=").append(areaId);
        sb.append(", cityId=").append(cityId);
        sb.append(", zoneId=").append(zoneId);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", developers=").append(developers);
        sb.append(", propertyCompany=").append(propertyCompany);
        sb.append(", coversArea=").append(coversArea);
        sb.append(", buildingArea=").append(buildingArea);
        sb.append(", totalHosing=").append(totalHosing);
        sb.append(", plotRatio=").append(plotRatio);
        sb.append(", greenRate=").append(greenRate);
        sb.append(", propertyCost=").append(propertyCost);
        sb.append(", decorateSituation=").append(decorateSituation);
        sb.append(", averagePrice=").append(averagePrice);
        sb.append(", elevatorProportion=").append(elevatorProportion);
        sb.append(", businessArea=").append(businessArea);
        sb.append(", parkingNumber=").append(parkingNumber);
        sb.append(", garageNumber=").append(garageNumber);
        sb.append(", operatorName=").append(operatorName);
        sb.append(", operatorPhone=").append(operatorPhone);
        sb.append(", lifeCompanion=").append(lifeCompanion);
        sb.append(", schoolCompanion=").append(schoolCompanion);
        sb.append(", trafficTravel=").append(trafficTravel);
        sb.append(", buildingType=").append(buildingType);
        sb.append(", consultantId=").append(consultantId);
        sb.append(", commissionInfo=").append(commissionInfo);
        sb.append(", reportRules=").append(reportRules);
        sb.append(", lookRules=").append(lookRules);
        sb.append(", dealRules=").append(dealRules);
        sb.append(", soluteRules=").append(soluteRules);
        sb.append(", othersRules=").append(othersRules);
        sb.append(", shelves=").append(shelves);
        sb.append(", travelProperty=").append(travelProperty);
        sb.append(", subwayLine=").append(subwayLine);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
    private String propertyType;

	public String getPropertyType() {
		return propertyType;
	}

	public void setPropertyType(String propertyType) {
		this.propertyType = propertyType;
	}
    
    
}