package com.fei.bean;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class SecondHouseOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.secOrderId
     *
     * @mbggenerated
     */
    private String secOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.secHouseId
     *
     * @mbggenerated
     */
    private String secHouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.agentId
     *
     * @mbggenerated
     */
    private String agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.clientName
     *
     * @mbggenerated
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.clientNumber
     *
     * @mbggenerated
     */
    private String clientNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.communityName
     *
     * @mbggenerated
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.roomNumber
     *
     * @mbggenerated
     */
    private String roomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.roomAddress
     *
     * @mbggenerated
     */
    private String roomAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.roomCerTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern ="yyyy-MM-dd HH:mm")
    private Date roomCerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.roomArea
     *
     * @mbggenerated
     */
    private String roomArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.roomCost
     *
     * @mbggenerated
     */
    private String roomCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.agency
     *
     * @mbggenerated
     */
    private String agency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.approveProgress
     *
     * @mbggenerated
     */
    private Integer approveProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.approvePer
     *
     * @mbggenerated
     */
    private String approvePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.approveTime
     *
     * @mbggenerated
     */
    private Date approveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.approveInfo
     *
     * @mbggenerated
     */
    private String approveInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_secondhouse_order.deleteFlag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_secondhouse_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.secOrderId
     *
     * @return the value of b_secondhouse_order.secOrderId
     *
     * @mbggenerated
     */
    public String getSecOrderId() {
        return secOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.secOrderId
     *
     * @param secOrderId the value for b_secondhouse_order.secOrderId
     *
     * @mbggenerated
     */
    public void setSecOrderId(String secOrderId) {
        this.secOrderId = secOrderId == null ? null : secOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.secHouseId
     *
     * @return the value of b_secondhouse_order.secHouseId
     *
     * @mbggenerated
     */
    public String getSecHouseId() {
        return secHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.secHouseId
     *
     * @param secHouseId the value for b_secondhouse_order.secHouseId
     *
     * @mbggenerated
     */
    public void setSecHouseId(String secHouseId) {
        this.secHouseId = secHouseId == null ? null : secHouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.agentId
     *
     * @return the value of b_secondhouse_order.agentId
     *
     * @mbggenerated
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.agentId
     *
     * @param agentId the value for b_secondhouse_order.agentId
     *
     * @mbggenerated
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.clientName
     *
     * @return the value of b_secondhouse_order.clientName
     *
     * @mbggenerated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.clientName
     *
     * @param clientName the value for b_secondhouse_order.clientName
     *
     * @mbggenerated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.clientNumber
     *
     * @return the value of b_secondhouse_order.clientNumber
     *
     * @mbggenerated
     */
    public String getClientNumber() {
        return clientNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.clientNumber
     *
     * @param clientNumber the value for b_secondhouse_order.clientNumber
     *
     * @mbggenerated
     */
    public void setClientNumber(String clientNumber) {
        this.clientNumber = clientNumber == null ? null : clientNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.communityName
     *
     * @return the value of b_secondhouse_order.communityName
     *
     * @mbggenerated
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.communityName
     *
     * @param communityName the value for b_secondhouse_order.communityName
     *
     * @mbggenerated
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.roomNumber
     *
     * @return the value of b_secondhouse_order.roomNumber
     *
     * @mbggenerated
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.roomNumber
     *
     * @param roomNumber the value for b_secondhouse_order.roomNumber
     *
     * @mbggenerated
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.roomAddress
     *
     * @return the value of b_secondhouse_order.roomAddress
     *
     * @mbggenerated
     */
    public String getRoomAddress() {
        return roomAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.roomAddress
     *
     * @param roomAddress the value for b_secondhouse_order.roomAddress
     *
     * @mbggenerated
     */
    public void setRoomAddress(String roomAddress) {
        this.roomAddress = roomAddress == null ? null : roomAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.roomCerTime
     *
     * @return the value of b_secondhouse_order.roomCerTime
     *
     * @mbggenerated
     */
    public Date getRoomCerTime() {
        return roomCerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.roomCerTime
     *
     * @param roomCerTime the value for b_secondhouse_order.roomCerTime
     *
     * @mbggenerated
     */
    public void setRoomCerTime(Date roomCerTime) {
        this.roomCerTime = roomCerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.roomArea
     *
     * @return the value of b_secondhouse_order.roomArea
     *
     * @mbggenerated
     */
    public String getRoomArea() {
        return roomArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.roomArea
     *
     * @param roomArea the value for b_secondhouse_order.roomArea
     *
     * @mbggenerated
     */
    public void setRoomArea(String roomArea) {
        this.roomArea = roomArea == null ? null : roomArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.roomCost
     *
     * @return the value of b_secondhouse_order.roomCost
     *
     * @mbggenerated
     */
    public String getRoomCost() {
        return roomCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.roomCost
     *
     * @param roomCost the value for b_secondhouse_order.roomCost
     *
     * @mbggenerated
     */
    public void setRoomCost(String roomCost) {
        this.roomCost = roomCost == null ? null : roomCost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.agency
     *
     * @return the value of b_secondhouse_order.agency
     *
     * @mbggenerated
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.agency
     *
     * @param agency the value for b_secondhouse_order.agency
     *
     * @mbggenerated
     */
    public void setAgency(String agency) {
        this.agency = agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.approveProgress
     *
     * @return the value of b_secondhouse_order.approveProgress
     *
     * @mbggenerated
     */
    public Integer getApproveProgress() {
        return approveProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.approveProgress
     *
     * @param approveProgress the value for b_secondhouse_order.approveProgress
     *
     * @mbggenerated
     */
    public void setApproveProgress(Integer approveProgress) {
        this.approveProgress = approveProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.approvePer
     *
     * @return the value of b_secondhouse_order.approvePer
     *
     * @mbggenerated
     */
    public String getApprovePer() {
        return approvePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.approvePer
     *
     * @param approvePer the value for b_secondhouse_order.approvePer
     *
     * @mbggenerated
     */
    public void setApprovePer(String approvePer) {
        this.approvePer = approvePer == null ? null : approvePer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.approveTime
     *
     * @return the value of b_secondhouse_order.approveTime
     *
     * @mbggenerated
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.approveTime
     *
     * @param approveTime the value for b_secondhouse_order.approveTime
     *
     * @mbggenerated
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.approveInfo
     *
     * @return the value of b_secondhouse_order.approveInfo
     *
     * @mbggenerated
     */
    public String getApproveInfo() {
        return approveInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.approveInfo
     *
     * @param approveInfo the value for b_secondhouse_order.approveInfo
     *
     * @mbggenerated
     */
    public void setApproveInfo(String approveInfo) {
        this.approveInfo = approveInfo == null ? null : approveInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.createUser
     *
     * @return the value of b_secondhouse_order.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.createUser
     *
     * @param createUser the value for b_secondhouse_order.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.createTime
     *
     * @return the value of b_secondhouse_order.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.createTime
     *
     * @param createTime the value for b_secondhouse_order.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.updateUser
     *
     * @return the value of b_secondhouse_order.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.updateUser
     *
     * @param updateUser the value for b_secondhouse_order.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.updateTime
     *
     * @return the value of b_secondhouse_order.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.updateTime
     *
     * @param updateTime the value for b_secondhouse_order.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_secondhouse_order.deleteFlag
     *
     * @return the value of b_secondhouse_order.deleteFlag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_secondhouse_order.deleteFlag
     *
     * @param deleteFlag the value for b_secondhouse_order.deleteFlag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_secondhouse_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SecondHouseOrder other = (SecondHouseOrder) that;
        return (this.getSecOrderId() == null ? other.getSecOrderId() == null : this.getSecOrderId().equals(other.getSecOrderId()))
            && (this.getSecHouseId() == null ? other.getSecHouseId() == null : this.getSecHouseId().equals(other.getSecHouseId()))
            && (this.getAgentId() == null ? other.getAgentId() == null : this.getAgentId().equals(other.getAgentId()))
            && (this.getClientName() == null ? other.getClientName() == null : this.getClientName().equals(other.getClientName()))
            && (this.getClientNumber() == null ? other.getClientNumber() == null : this.getClientNumber().equals(other.getClientNumber()))
            && (this.getCommunityName() == null ? other.getCommunityName() == null : this.getCommunityName().equals(other.getCommunityName()))
            && (this.getRoomNumber() == null ? other.getRoomNumber() == null : this.getRoomNumber().equals(other.getRoomNumber()))
            && (this.getRoomAddress() == null ? other.getRoomAddress() == null : this.getRoomAddress().equals(other.getRoomAddress()))
            && (this.getRoomCerTime() == null ? other.getRoomCerTime() == null : this.getRoomCerTime().equals(other.getRoomCerTime()))
            && (this.getRoomArea() == null ? other.getRoomArea() == null : this.getRoomArea().equals(other.getRoomArea()))
            && (this.getRoomCost() == null ? other.getRoomCost() == null : this.getRoomCost().equals(other.getRoomCost()))
            && (this.getAgency() == null ? other.getAgency() == null : this.getAgency().equals(other.getAgency()))
            && (this.getApproveProgress() == null ? other.getApproveProgress() == null : this.getApproveProgress().equals(other.getApproveProgress()))
            && (this.getApprovePer() == null ? other.getApprovePer() == null : this.getApprovePer().equals(other.getApprovePer()))
            && (this.getApproveTime() == null ? other.getApproveTime() == null : this.getApproveTime().equals(other.getApproveTime()))
            && (this.getApproveInfo() == null ? other.getApproveInfo() == null : this.getApproveInfo().equals(other.getApproveInfo()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_secondhouse_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecOrderId() == null) ? 0 : getSecOrderId().hashCode());
        result = prime * result + ((getSecHouseId() == null) ? 0 : getSecHouseId().hashCode());
        result = prime * result + ((getAgentId() == null) ? 0 : getAgentId().hashCode());
        result = prime * result + ((getClientName() == null) ? 0 : getClientName().hashCode());
        result = prime * result + ((getClientNumber() == null) ? 0 : getClientNumber().hashCode());
        result = prime * result + ((getCommunityName() == null) ? 0 : getCommunityName().hashCode());
        result = prime * result + ((getRoomNumber() == null) ? 0 : getRoomNumber().hashCode());
        result = prime * result + ((getRoomAddress() == null) ? 0 : getRoomAddress().hashCode());
        result = prime * result + ((getRoomCerTime() == null) ? 0 : getRoomCerTime().hashCode());
        result = prime * result + ((getRoomArea() == null) ? 0 : getRoomArea().hashCode());
        result = prime * result + ((getRoomCost() == null) ? 0 : getRoomCost().hashCode());
        result = prime * result + ((getAgency() == null) ? 0 : getAgency().hashCode());
        result = prime * result + ((getApproveProgress() == null) ? 0 : getApproveProgress().hashCode());
        result = prime * result + ((getApprovePer() == null) ? 0 : getApprovePer().hashCode());
        result = prime * result + ((getApproveTime() == null) ? 0 : getApproveTime().hashCode());
        result = prime * result + ((getApproveInfo() == null) ? 0 : getApproveInfo().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_secondhouse_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", secOrderId=").append(secOrderId);
        sb.append(", secHouseId=").append(secHouseId);
        sb.append(", agentId=").append(agentId);
        sb.append(", clientName=").append(clientName);
        sb.append(", clientNumber=").append(clientNumber);
        sb.append(", communityName=").append(communityName);
        sb.append(", roomNumber=").append(roomNumber);
        sb.append(", roomAddress=").append(roomAddress);
        sb.append(", roomCerTime=").append(roomCerTime);
        sb.append(", roomArea=").append(roomArea);
        sb.append(", roomCost=").append(roomCost);
        sb.append(", agency=").append(agency);
        sb.append(", approveProgress=").append(approveProgress);
        sb.append(", approvePer=").append(approvePer);
        sb.append(", approveTime=").append(approveTime);
        sb.append(", approveInfo=").append(approveInfo);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}