package com.fei.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.fei.bean.ApartmentNew;
import com.fei.bean.ApartmentNewExample;

public interface ApartmentNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int countByExample(ApartmentNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int deleteByExample(ApartmentNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String apartmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int insert(ApartmentNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int insertSelective(ApartmentNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    List<Map<String, Object>> selectByExample(ApartmentNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    ApartmentNew selectByPrimaryKey(String apartmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApartmentNew record, @Param("example") ApartmentNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApartmentNew record, @Param("example") ApartmentNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApartmentNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_apartment_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApartmentNew record);
}