package com.fei.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.fei.bean.BaseInfo;
import com.fei.bean.BaseInfoExample;
import com.fei.bean.BaseInfoKey;

public interface BaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int countByExample(BaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int deleteByExample(BaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BaseInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int insert(BaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int insertSelective(BaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    List<BaseInfo> selectByExample(BaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    BaseInfo selectByPrimaryKey(BaseInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseInfo record, @Param("example") BaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseInfo record, @Param("example") BaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_baseinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseInfo record);
}