package com.fei.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.fei.bean.Company;
import com.fei.bean.CompanyExample;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    Company selectByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Company record);
}