package com.fei.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.fei.bean.Problem;
import com.fei.bean.ProblemExample;

public interface ProblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int countByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int deleteByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String problemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int insert(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int insertSelective(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    List<Problem> selectByExampleWithBLOBs(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    List<Problem> selectByExample(ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    Problem selectByPrimaryKey(String problemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Problem record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Problem record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Problem record, @Param("example") ProblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Problem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_problem
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Problem record);
}