package com.fei.vo;

import java.io.Serializable;
import java.util.Date;

public class BuildingOldVo extends BasePageVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.buildingOldId
     *
     * @mbggenerated
     */
    private String buildingOldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.buildingOldTitle
     *
     * @mbggenerated
     */
    private String buildingOldTitle;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.kitchen
     *
     * @mbggenerated
     */
    private Integer kitchen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.bedRoom
     *
     * @mbggenerated
     */
    private Integer bedRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.livingRoom
     *
     * @mbggenerated
     */
    private Integer livingRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.guard
     *
     * @mbggenerated
     */
    private Integer guard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.floor
     *
     * @mbggenerated
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.allFloor
     *
     * @mbggenerated
     */
    private Integer allFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.floorType
     *
     * @mbggenerated
     */
    private Integer floorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.orientation
     *
     * @mbggenerated
     */
    private String orientation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.decorateSituation
     *
     * @mbggenerated
     */
    private Integer decorateSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.isElevator
     *
     * @mbggenerated
     */
    private Integer isElevator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.isHeating
     *
     * @mbggenerated
     */
    private Integer isHeating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.years
     *
     * @mbggenerated
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.areaId
     *
     * @mbggenerated
     */
    private String areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.cityId
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.zoneId
     *
     * @mbggenerated
     */
    private String zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.detailAddress
     *
     * @mbggenerated
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.longitude
     *
     * @mbggenerated
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.latitude
     *
     * @mbggenerated
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.buildingId
     *
     * @mbggenerated
     */
    private String buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.isFive
     *
     * @mbggenerated
     */
    private Integer isFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.isOnly
     *
     * @mbggenerated
     */
    private Integer isOnly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.isTwo
     *
     * @mbggenerated
     */
    private Integer isTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.schoolDistrict
     *
     * @mbggenerated
     */
    private String schoolDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.metro
     *
     * @mbggenerated
     */
    private String metro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.shelves
     *
     * @mbggenerated
     */
    private Integer shelves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_building_old.deleteFlag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_building_old
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.buildingOldId
     *
     * @return the value of b_building_old.buildingOldId
     *
     * @mbggenerated
     */
    public String getBuildingOldId() {
        return buildingOldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.buildingOldId
     *
     * @param buildingOldId the value for b_building_old.buildingOldId
     *
     * @mbggenerated
     */
    public void setBuildingOldId(String buildingOldId) {
        this.buildingOldId = buildingOldId == null ? null : buildingOldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.kitchen
     *
     * @return the value of b_building_old.kitchen
     *
     * @mbggenerated
     */
    public Integer getKitchen() {
        return kitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.kitchen
     *
     * @param kitchen the value for b_building_old.kitchen
     *
     * @mbggenerated
     */
    public void setKitchen(Integer kitchen) {
        this.kitchen = kitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.bedRoom
     *
     * @return the value of b_building_old.bedRoom
     *
     * @mbggenerated
     */
    public Integer getBedRoom() {
        return bedRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.bedRoom
     *
     * @param bedRoom the value for b_building_old.bedRoom
     *
     * @mbggenerated
     */
    public void setBedRoom(Integer bedRoom) {
        this.bedRoom = bedRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.livingRoom
     *
     * @return the value of b_building_old.livingRoom
     *
     * @mbggenerated
     */
    public Integer getLivingRoom() {
        return livingRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.livingRoom
     *
     * @param livingRoom the value for b_building_old.livingRoom
     *
     * @mbggenerated
     */
    public void setLivingRoom(Integer livingRoom) {
        this.livingRoom = livingRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.guard
     *
     * @return the value of b_building_old.guard
     *
     * @mbggenerated
     */
    public Integer getGuard() {
        return guard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.guard
     *
     * @param guard the value for b_building_old.guard
     *
     * @mbggenerated
     */
    public void setGuard(Integer guard) {
        this.guard = guard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.floor
     *
     * @return the value of b_building_old.floor
     *
     * @mbggenerated
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.floor
     *
     * @param floor the value for b_building_old.floor
     *
     * @mbggenerated
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.allFloor
     *
     * @return the value of b_building_old.allFloor
     *
     * @mbggenerated
     */
    public Integer getAllFloor() {
        return allFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.allFloor
     *
     * @param allFloor the value for b_building_old.allFloor
     *
     * @mbggenerated
     */
    public void setAllFloor(Integer allFloor) {
        this.allFloor = allFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.floorType
     *
     * @return the value of b_building_old.floorType
     *
     * @mbggenerated
     */
    public Integer getFloorType() {
        return floorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.floorType
     *
     * @param floorType the value for b_building_old.floorType
     *
     * @mbggenerated
     */
    public void setFloorType(Integer floorType) {
        this.floorType = floorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.orientation
     *
     * @return the value of b_building_old.orientation
     *
     * @mbggenerated
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.orientation
     *
     * @param orientation the value for b_building_old.orientation
     *
     * @mbggenerated
     */
    public void setOrientation(String orientation) {
        this.orientation = orientation == null ? null : orientation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.decorateSituation
     *
     * @return the value of b_building_old.decorateSituation
     *
     * @mbggenerated
     */
    public Integer getDecorateSituation() {
        return decorateSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.decorateSituation
     *
     * @param decorateSituation the value for b_building_old.decorateSituation
     *
     * @mbggenerated
     */
    public void setDecorateSituation(Integer decorateSituation) {
        this.decorateSituation = decorateSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.isElevator
     *
     * @return the value of b_building_old.isElevator
     *
     * @mbggenerated
     */
    public Integer getIsElevator() {
        return isElevator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.isElevator
     *
     * @param isElevator the value for b_building_old.isElevator
     *
     * @mbggenerated
     */
    public void setIsElevator(Integer isElevator) {
        this.isElevator = isElevator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.isHeating
     *
     * @return the value of b_building_old.isHeating
     *
     * @mbggenerated
     */
    public Integer getIsHeating() {
        return isHeating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.isHeating
     *
     * @param isHeating the value for b_building_old.isHeating
     *
     * @mbggenerated
     */
    public void setIsHeating(Integer isHeating) {
        this.isHeating = isHeating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.years
     *
     * @return the value of b_building_old.years
     *
     * @mbggenerated
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.years
     *
     * @param years the value for b_building_old.years
     *
     * @mbggenerated
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.areaId
     *
     * @return the value of b_building_old.areaId
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.areaId
     *
     * @param areaId the value for b_building_old.areaId
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.cityId
     *
     * @return the value of b_building_old.cityId
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.cityId
     *
     * @param cityId the value for b_building_old.cityId
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.zoneId
     *
     * @return the value of b_building_old.zoneId
     *
     * @mbggenerated
     */
    public String getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.zoneId
     *
     * @param zoneId the value for b_building_old.zoneId
     *
     * @mbggenerated
     */
    public void setZoneId(String zoneId) {
        this.zoneId = zoneId == null ? null : zoneId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.detailAddress
     *
     * @return the value of b_building_old.detailAddress
     *
     * @mbggenerated
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.detailAddress
     *
     * @param detailAddress the value for b_building_old.detailAddress
     *
     * @mbggenerated
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.longitude
     *
     * @return the value of b_building_old.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.longitude
     *
     * @param longitude the value for b_building_old.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.latitude
     *
     * @return the value of b_building_old.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.latitude
     *
     * @param latitude the value for b_building_old.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.buildingId
     *
     * @return the value of b_building_old.buildingId
     *
     * @mbggenerated
     */
    public String getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.buildingId
     *
     * @param buildingId the value for b_building_old.buildingId
     *
     * @mbggenerated
     */
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId == null ? null : buildingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.price
     *
     * @return the value of b_building_old.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.price
     *
     * @param price the value for b_building_old.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.area
     *
     * @return the value of b_building_old.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.area
     *
     * @param area the value for b_building_old.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.isFive
     *
     * @return the value of b_building_old.isFive
     *
     * @mbggenerated
     */
    public Integer getIsFive() {
        return isFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.isFive
     *
     * @param isFive the value for b_building_old.isFive
     *
     * @mbggenerated
     */
    public void setIsFive(Integer isFive) {
        this.isFive = isFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.isOnly
     *
     * @return the value of b_building_old.isOnly
     *
     * @mbggenerated
     */
    public Integer getIsOnly() {
        return isOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.isOnly
     *
     * @param isOnly the value for b_building_old.isOnly
     *
     * @mbggenerated
     */
    public void setIsOnly(Integer isOnly) {
        this.isOnly = isOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.isTwo
     *
     * @return the value of b_building_old.isTwo
     *
     * @mbggenerated
     */
    public Integer getIsTwo() {
        return isTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.isTwo
     *
     * @param isTwo the value for b_building_old.isTwo
     *
     * @mbggenerated
     */
    public void setIsTwo(Integer isTwo) {
        this.isTwo = isTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.schoolDistrict
     *
     * @return the value of b_building_old.schoolDistrict
     *
     * @mbggenerated
     */
    public String getSchoolDistrict() {
        return schoolDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.schoolDistrict
     *
     * @param schoolDistrict the value for b_building_old.schoolDistrict
     *
     * @mbggenerated
     */
    public void setSchoolDistrict(String schoolDistrict) {
        this.schoolDistrict = schoolDistrict == null ? null : schoolDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.metro
     *
     * @return the value of b_building_old.metro
     *
     * @mbggenerated
     */
    public String getMetro() {
        return metro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.metro
     *
     * @param metro the value for b_building_old.metro
     *
     * @mbggenerated
     */
    public void setMetro(String metro) {
        this.metro = metro == null ? null : metro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.shelves
     *
     * @return the value of b_building_old.shelves
     *
     * @mbggenerated
     */
    public Integer getShelves() {
        return shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.shelves
     *
     * @param shelves the value for b_building_old.shelves
     *
     * @mbggenerated
     */
    public void setShelves(Integer shelves) {
        this.shelves = shelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.createUser
     *
     * @return the value of b_building_old.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.createUser
     *
     * @param createUser the value for b_building_old.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.createTime
     *
     * @return the value of b_building_old.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.createTime
     *
     * @param createTime the value for b_building_old.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.updateUser
     *
     * @return the value of b_building_old.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.updateUser
     *
     * @param updateUser the value for b_building_old.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.updateTime
     *
     * @return the value of b_building_old.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.updateTime
     *
     * @param updateTime the value for b_building_old.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_building_old.deleteFlag
     *
     * @return the value of b_building_old.deleteFlag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_building_old.deleteFlag
     *
     * @param deleteFlag the value for b_building_old.deleteFlag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
    
    

    public String getBuildingOldTitle() {
		return buildingOldTitle;
	}

	public void setBuildingOldTitle(String buildingOldTitle) {
		this.buildingOldTitle = buildingOldTitle;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_building_old
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BuildingOldVo other = (BuildingOldVo) that;
        return (this.getBuildingOldId() == null ? other.getBuildingOldId() == null : this.getBuildingOldId().equals(other.getBuildingOldId()))
            && (this.getKitchen() == null ? other.getKitchen() == null : this.getKitchen().equals(other.getKitchen()))
            && (this.getBedRoom() == null ? other.getBedRoom() == null : this.getBedRoom().equals(other.getBedRoom()))
            && (this.getLivingRoom() == null ? other.getLivingRoom() == null : this.getLivingRoom().equals(other.getLivingRoom()))
            && (this.getGuard() == null ? other.getGuard() == null : this.getGuard().equals(other.getGuard()))
            && (this.getFloor() == null ? other.getFloor() == null : this.getFloor().equals(other.getFloor()))
            && (this.getAllFloor() == null ? other.getAllFloor() == null : this.getAllFloor().equals(other.getAllFloor()))
            && (this.getFloorType() == null ? other.getFloorType() == null : this.getFloorType().equals(other.getFloorType()))
            && (this.getOrientation() == null ? other.getOrientation() == null : this.getOrientation().equals(other.getOrientation()))
            && (this.getDecorateSituation() == null ? other.getDecorateSituation() == null : this.getDecorateSituation().equals(other.getDecorateSituation()))
            && (this.getIsElevator() == null ? other.getIsElevator() == null : this.getIsElevator().equals(other.getIsElevator()))
            && (this.getIsHeating() == null ? other.getIsHeating() == null : this.getIsHeating().equals(other.getIsHeating()))
            && (this.getYears() == null ? other.getYears() == null : this.getYears().equals(other.getYears()))
            && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getZoneId() == null ? other.getZoneId() == null : this.getZoneId().equals(other.getZoneId()))
            && (this.getDetailAddress() == null ? other.getDetailAddress() == null : this.getDetailAddress().equals(other.getDetailAddress()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getBuildingId() == null ? other.getBuildingId() == null : this.getBuildingId().equals(other.getBuildingId()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getIsFive() == null ? other.getIsFive() == null : this.getIsFive().equals(other.getIsFive()))
            && (this.getIsOnly() == null ? other.getIsOnly() == null : this.getIsOnly().equals(other.getIsOnly()))
            && (this.getIsTwo() == null ? other.getIsTwo() == null : this.getIsTwo().equals(other.getIsTwo()))
            && (this.getSchoolDistrict() == null ? other.getSchoolDistrict() == null : this.getSchoolDistrict().equals(other.getSchoolDistrict()))
            && (this.getMetro() == null ? other.getMetro() == null : this.getMetro().equals(other.getMetro()))
            && (this.getShelves() == null ? other.getShelves() == null : this.getShelves().equals(other.getShelves()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_building_old
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBuildingOldId() == null) ? 0 : getBuildingOldId().hashCode());
        result = prime * result + ((getKitchen() == null) ? 0 : getKitchen().hashCode());
        result = prime * result + ((getBedRoom() == null) ? 0 : getBedRoom().hashCode());
        result = prime * result + ((getLivingRoom() == null) ? 0 : getLivingRoom().hashCode());
        result = prime * result + ((getGuard() == null) ? 0 : getGuard().hashCode());
        result = prime * result + ((getFloor() == null) ? 0 : getFloor().hashCode());
        result = prime * result + ((getAllFloor() == null) ? 0 : getAllFloor().hashCode());
        result = prime * result + ((getFloorType() == null) ? 0 : getFloorType().hashCode());
        result = prime * result + ((getOrientation() == null) ? 0 : getOrientation().hashCode());
        result = prime * result + ((getDecorateSituation() == null) ? 0 : getDecorateSituation().hashCode());
        result = prime * result + ((getIsElevator() == null) ? 0 : getIsElevator().hashCode());
        result = prime * result + ((getIsHeating() == null) ? 0 : getIsHeating().hashCode());
        result = prime * result + ((getYears() == null) ? 0 : getYears().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getZoneId() == null) ? 0 : getZoneId().hashCode());
        result = prime * result + ((getDetailAddress() == null) ? 0 : getDetailAddress().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getBuildingId() == null) ? 0 : getBuildingId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getIsFive() == null) ? 0 : getIsFive().hashCode());
        result = prime * result + ((getIsOnly() == null) ? 0 : getIsOnly().hashCode());
        result = prime * result + ((getIsTwo() == null) ? 0 : getIsTwo().hashCode());
        result = prime * result + ((getSchoolDistrict() == null) ? 0 : getSchoolDistrict().hashCode());
        result = prime * result + ((getMetro() == null) ? 0 : getMetro().hashCode());
        result = prime * result + ((getShelves() == null) ? 0 : getShelves().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_building_old
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", buildingOldId=").append(buildingOldId);
        sb.append(", kitchen=").append(kitchen);
        sb.append(", bedRoom=").append(bedRoom);
        sb.append(", livingRoom=").append(livingRoom);
        sb.append(", guard=").append(guard);
        sb.append(", floor=").append(floor);
        sb.append(", allFloor=").append(allFloor);
        sb.append(", floorType=").append(floorType);
        sb.append(", orientation=").append(orientation);
        sb.append(", decorateSituation=").append(decorateSituation);
        sb.append(", isElevator=").append(isElevator);
        sb.append(", isHeating=").append(isHeating);
        sb.append(", years=").append(years);
        sb.append(", areaId=").append(areaId);
        sb.append(", cityId=").append(cityId);
        sb.append(", zoneId=").append(zoneId);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", buildingId=").append(buildingId);
        sb.append(", price=").append(price);
        sb.append(", area=").append(area);
        sb.append(", isFive=").append(isFive);
        sb.append(", isOnly=").append(isOnly);
        sb.append(", isTwo=").append(isTwo);
        sb.append(", schoolDistrict=").append(schoolDistrict);
        sb.append(", metro=").append(metro);
        sb.append(", shelves=").append(shelves);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
    
 private String cityName;
    
    private String zoneName;

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getZoneName() {
		return zoneName;
	}

	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}
	
	
    
    
}